version: '3.9'
services:
  db:
    container_name: db
    image: luck3rinc/bonchmafia_db:latest
    restart: always
    environment:
      POSTGRES_USER: $USER
      POSTGRES_PASSWORD: $PASSWORD
      POSTGRES_DB: $DB
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - ./postgresql/data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $MAIL
      PGADMIN_DEFAULT_PASSWORD: $PASS
    ports:
      - "80:80"

  main:
    container_name: bonchmafia
    image: luck3rinc/bonchmafia:latest
    restart: on-failure
    environment:
      API_TOKEN: $API_TOKEN
      HOST: $HOST
      DB: $DB
      USER: $USER
      PASSWORD: $PASSWORD
      ADMIN: $ADMIN
      PORT: $PORT
    volumes:
      - ./logs:/~/BonchMafia/logs
      - ./bot/pictures:/~/BonchMafia/bot/pictures
    depends_on:
      - db

volumes:
  logs: